version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sslmonitor
      POSTGRES_USER: sslmonitor
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ssl-monitor:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sslmonitor
      DB_USERNAME: sslmonitor
      DB_PASSWORD: password123

volumes:
  postgres_data: