version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sslmonitor-postgres
    environment:
      POSTGRES_DB: sslmonitor
      POSTGRES_USER: sslmonitor
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: